
  version: '3'
  services:
    web:
      build:
        context: .
        dockerfile: .docker/Dockerfile
      container_name: hello_world_web_hakan_1
      ports:
        - 8003:80
      volumes:
        - .:/srv/app
      depends_on:
        - mysql
    mysql:
      image: mysql:5.7
      container_name: hello_world_mysql_hakan_1
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: todos
        MYSQL_USER: todos-user
        MYSQL_PASSWORD: todos-pwd
      ports:
        - 8004:3306
      volumes:
        - .docker/:/docker-entrypoint-initdb.d