
  version: '3'
  services:
    api:
      build:
        context: api/
        dockerfile: .docker/Dockerfile
      container_name: todoApi
      ports:
        - 8005:80
      volumes:
        - ./api:/srv/api
      depends_on:
        - mysql
    site:
        build:
          context: site/
          dockerfile: .docker/Dockerfile
        container_name: todoWeb
        ports:
          - 8003:80
        volumes:
          - ./site:/srv/site
        depends_on:
          - api
    mysql:
      image: mysql:5.7
      container_name: todoSql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: todos
        MYSQL_USER: todos-user
        MYSQL_PASSWORD: todos-pwd
      ports:
        - 8004:3306
      volumes:
        - ./api/.docker/:/docker-entrypoint-initdb.d
